### ISSUE TITLE
Check URL encoding for HDL contained URLs

### ISSUE THREAD

**Issue by fungunga** [tify-iiif-viewer/tify#130]
Our manifest URL is <https://trep.de.dariah.eu/1.0/iiif/manifests/hdl:21.T11991%2F0000-0011-B8C6-E/manifest.json> (yes, dull HDL it is).

To get the correct TIFY call with this URL, we have to double URL encode it:
<https://demo.tify.rocks/demo.html?manifest=https://trep.de.dariah.eu/1.0/iiif/manifests/hdl:21.T11991%252F0000-0011-B8C6-E/manifest.json>

<https://demo.tify.rocks/demo.html?manifest=https://trep.de.dariah.eu/1.0/iiif/manifests/hdl:21.T11991%2F0000-0011-B8C6-E/manifest.json> is not working.

Is this the correct behaviour? Is it an error on our side? If so, please close the issue right away... :-)

**Comment by t11r** [comment]
Who puts encoded slashes in their URL? :wink:

You have to stick to the first option, because we cannot keep the URL parser from decoding `%2F` to `/`. The original URL should work fine when used with the `manifestUrl` option, which is what you would do when you embed TIFY into your website anyway.

To avoid a redirect, please link to the current website when sharing the link (with correctly escaped reserved characters): https://tify.rocks/?manifest=https%3A%2F%2Ftrep.de.dariah.eu%2F1.0%2Fiiif%2Fmanifests%2Fhdl%3A21.T11991%252F0000-0011-B8C6-E%2Fmanifest.json

**Comment by fungunga** [comment]
We don't, HDL and DOI people do :-D

Fine, so I implement URL encoding for the complete URL, makes it a tiny little bit better! :-) Thanks!
