### ISSUE TITLE
Problem getting tify to run in Vue 2.3 Single File Component

### ISSUE THREAD

**Issue by arjanski** [tify-iiif-viewer/tify#7]
Hello, 

I'm wondering what I am doing wrong?  I keep getting the following errors:

> vue-router.esm.js?fe87:16 [vue-router] Failed to resolve async component default: Error: TIFY container element not found
> vue-router.esm.js?fe87:1832 Error: TIFY container element not found

Here's my code (excerpts):

Here is my Vue component using Tify (it's a single file component):

Template:
`
    <template>
       <div>
          <div id="tify" style="position: relative; width: 800px; height: 600px;"></div>
      </div>
    </template>
`

Script:

      require ('../../../iiif/tify.js')
      require ('../../../iiif/tify.css')

      let tifyOptions = {
          container: '#tify',
          language: 'de',
          manifestUrl: 'https://rawgit.com/pdaengeli/9866a1a01be9a806d82bcfb7305eaee2/raw/ca81647167842403ee503a964288eb2805dd6e49/letter_16636_manifest.json'
        }

Anyone has an idea what I am getting wrong?

**Comment by t11r** [comment]
Hi Arjan,

I’m assuming you are using the compiled TIFY files from the `dist` directory.

TIFY is distributed as an IIFE, which means the script executes upon load. Thus the `tifyOptions` object has to be set prior to the `require` statements, which in turn – as you may already know, just for sake of completeness – must be run by Vue’s `mounted` hook; only then will your template be part of the DOM tree. Instead of requiring the stylesheet, let TIFY handle its styles by setting the `stylesheet` option if needed.

Additionally, you could use a `$ref` for the container. Since v0.15.0, TIFY supports an `HTMLElement` for the `container` option.

Please note that the options `manifestUrl` and `stylesheetUrl` have been renamed to `manifest` and `stylesheet` respectively with the latest release.

Hope this helps!

**Comment by doganzm** [comment]
Try putting the javascript after the tify div!

**Comment by arjanski** [comment]
@tschaef Thank you for your response!

A small follow-up to my problem. I am still getting the error above and was wondering what is still missing, having followed your instructions:

1) I am using the tify files from the /dist directory, yes. Version 0.17.1
2) Vue version is the latest 2.5.3
3) In my template, the container div reads as follows:  
```
<div id="tify" style="height: 500px; width: 500px; position: relative; margin-left: 20px">
</div>
```
4) In the 'mounted' hook, I am setting the tify-Options like this:
```
  mounted() {
    var tifyOptions = {
      container: '#tify',
      language: 'de',
      manifest: 'https://rawgit.com/pdaengeli/9866a1a01be9a806d82bcfb7305eaee2/raw/ca81647167842403ee503a964288eb2805dd6e49/letter_16636_manifest.json'
    }
  },
```
5) Finally, in the <script> section I am loading the tify.js (got rid of the tify.css)
```
require ('../../../iiif/tify.js')
```

So I have updated to the newest versions, using the new 'manifest' parameter. Unfortunately, the console error still says that it cannot find the container div, resulting in the page not getting loaded at all:

```
[vue-router] Failed to resolve async component default: Error: TIFY container element not found
13:42:06.849 vue-router.esm.js?fe87:16 [vue-router] uncaught error during route navigation:
13:42:06.850 vue-router.esm.js?fe87:1905 Error: TIFY container element not found
```

Do you have any idea what is missing here? Thanks a lot for your time and help, highly appreciated!

**Comment by t11r** [comment]
Sounds fine, except for step 5: TIFY should be loaded by the Vue app, not inside a separate `<script>` element. I created [a short fiddle](http://jsfiddle.net/cqt24a4q/9/), which hopefully points you in the right direction.

With one of the upcoming releases, it will be possible to `import` TIFY and call an `init` function from within a Vue app.

**Comment by arjanski** [comment]
Hey thank you for the effort! Will look into this again. My project is setup as single file components, so I'll have to factor that in. Also, I'm pretty much new to Vue/webapps, so thank you for your patience!

Best wishes to Göttingen

**Comment by arjanski** [comment]
Unfortunately I probably won't be able to use Tify without an `import` - is there a rough roadmap for this feature maybe? We're doing a university project and would very much like to use it nonetheless.

**Comment by t11r** [comment]
Happy to help! I will keep an eye out for your upcoming Vue- and TIFY-based project.

I cannot make any promises for the `import` feature, but it will most likely be implemented by the end of the month. Anyway, as shown in the example, you should be able to `require` TIFY, which itself is composed of single file Vue components, and all the OpenSeadragon modules are loaded via `require`.

**Comment by polyrainbow** [comment]
An import feature or a way to dynamically initialize TIFY (instead of the plugin loading on script load) would be great indeed in my opinion, especially considering the typical workflow in dynamic SPAs.

**Comment by t11r** [comment]
You can now prevent TIFY from running upon load by setting `tifyOptions = { init: false }`.

Support for ES6 `import` will unfortunately be delayed until further notice. Feel free to contribute :wink:
If you are creating a Vue app, you might be better off importing TIFY’s Vue source files instead of the compiled JS.

**Comment by arjanski** [comment]
Great, thank you very much for the quick fix!
